Feat/client
LaurisHebert/com.simplon.dvd pull request #1
Opened 2023-09-21 10:15 UTC by LaurisHebert

Ajout du Mapping Client

2023-09-21 10:36 UTC, Mekouar-Ayoub requested changes

2023-09-21 10:36 UTC, Mekouar-Ayoub commented on src/main/java/com/simplon/dvd/DvdApplication.java
> +// ajouter MapStruct au projet
ben voilà :D

2023-09-21 10:36 UTC, Mekouar-Ayoub commented on src/main/java/com/simplon/dvd/entitys/ClientEntity.java
> +    private String clientNumber; // clientId ? clientTag ? trouver un nom
ClientReference

2023-09-21 10:36 UTC, Mekouar-Ayoub commented on src/main/java/com/simplon/dvd/services/ClientService.java
> +        return new ClientServiceModel(repository.findById(id).orElseThrow());
Exception personnalisée

2023-09-21 10:36 UTC, Mekouar-Ayoub commented on src/main/java/com/simplon/dvd/services/ClientService.java
> +        repository.save(new ClientEntity(client));
Essaies de plutot appeller tes entity Repository model. pourquoi à ton avis ?

2023-09-21 10:36 UTC, Mekouar-Ayoub commented on src/main/java/com/simplon/dvd/services/ClientServiceModel.java
> +        this.clientNumber = client.getClientNumber();
Reference

2023-09-21 10:36 UTC, Mekouar-Ayoub commented on src/main/java/com/simplon/dvd/services/ClientServiceModel.java
> +        this.clientNumber = client.clientNumber();
same

2023-09-21 10:36 UTC, Mekouar-Ayoub commented on src/main/java/com/simplon/dvd/services/ClientServiceModel.java
> +        this.clientNumber = client.clientNumber();
same

2023-09-21 10:53 UTC, LaurisHebert commented on src/main/java/com/simplon/dvd/services/ClientService.java
> +        repository.save(new ClientEntity(client));
Pour la même raison que les Services et ServiceModels ?

2023-09-22 07:45 UTC, LaurisHebert commented on src/main/java/com/simplon/dvd/services/ClientService.java
> +        repository.save(new ClientEntity(client));
Pour ne pas confondre deux ClientEntity qui serviraient chacun pour un type de stockage différent

2023-09-26 17:36 UTC, LaurisHebert commented on src/main/java/com/simplon/dvd/DvdApplication.java
> +// ajouter MapStruct au projet
Done

2023-09-26 21:04 UTC, closed without merging