Feat/dvd
LaurisHebert/com.simplon.dvd pull request #2
Opened 2023-09-21 10:16 UTC by LaurisHebert

Mapping dvd

2023-09-21 10:32 UTC, Mekouar-Ayoub approved these changes

2023-09-21 10:32 UTC, Mekouar-Ayoub commented on src/main/java/com/simplon/dvd/services/DvdService.java
> +        return new DvdServiceModel(repository.findById(id).orElseThrow());
Créer une exception personnalisée

2023-09-21 10:32 UTC, Mekouar-Ayoub commented on src/main/java/com/simplon/dvd/services/DvdServiceModel.java
> +    public DvdServiceModel(DvdEntity dvd) {
Utilise Map Struct

2023-09-21 10:32 UTC, Mekouar-Ayoub commented on src/main/resources/application.properties
> +spring.datasource.username = root
Comment tu pense que tu peux guarantir qu'une personne mal intentionnée ne puisse pas voir tes identifiants

2023-09-21 10:32 UTC, Mekouar-Ayoub requested changes
Utilise Map Struct

2023-09-21 10:52 UTC, LaurisHebert commented on src/main/resources/application.properties
> +spring.datasource.username = root
En l'ajoutant au gitIgnore ?

2023-09-26 17:36 UTC, LaurisHebert commented on src/main/java/com/simplon/dvd/services/DvdServiceModel.java
> +    public DvdServiceModel(DvdEntity dvd) {
Done

2023-09-26 17:37 UTC, closed without merging